#!/bin/sh
# This script runs osu! using `wine`.
# You need to setup wineprefix using `lutris`.

killall xcompmgr >/dev/null 2>&1
export PATH=/opt/wine-osu/bin:$PATH
export WINEPREFIX=~/Games/osu/
cd ~/Games/osu/drive_c/osu

wine osu\!.exe
